iglesys_index:
    resource: "@IglesysIndexBundle/Resources/config/routing.yml"
    prefix:   /

iglesys_ganados:
    resource: "@IglesysGanadosBundle/Resources/config/routing.yml"
    prefix:   /

iglesys_general:
    resource: "@IglesysGeneralBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
