valorvariable:
    path:     /
    defaults: { _controller: "IglesysGeneralBundle:ValorVariable:index" }

valorvariable_show:
    path:     /{id}/show
    defaults: { _controller: "IglesysGeneralBundle:ValorVariable:show" }

valorvariable_new:
    path:     /new
    defaults: { _controller: "IglesysGeneralBundle:ValorVariable:new" }

valorvariable_create:
    path:     /create
    defaults: { _controller: "IglesysGeneralBundle:ValorVariable:create" }
    methods:  POST

valorvariable_edit:
    path:     /{id}/edit
    defaults: { _controller: "IglesysGeneralBundle:ValorVariable:edit" }

valorvariable_update:
    path:     /{id}/update
    defaults: { _controller: "IglesysGeneralBundle:ValorVariable:update" }
    methods:  [POST, PUT]

valorvariable_delete:
    path:     /{id}/delete
    defaults: { _controller: "IglesysGeneralBundle:ValorVariable:delete" }
    methods:  [POST, DELETE]
