iglesys_ganados_index:
    path:     /ganados/
    defaults: { _controller: IglesysGanadosBundle:Default:index}
    methods: [GET]

iglesys_ganados_create:
    path:     /ganados/{q}
    defaults: { _controller: IglesysGanadosBundle:Default:create}
    methods: [POST]

iglesys_ganados_show:
    path:     /ganados/{id}
    defaults: { _controller: IglesysGanadosBundle:Default:show}
    methods: [GET]

iglesys_ganados_update:
    path:     /ganados/{id}
    defaults: { _controller: IglesysGanadosBundle:Default:update}
    methods: [PUT]

iglesys_ganados_delete:
    path:     /ganados/{id}
    defaults: { _controller: IglesysGanadosBundle:Default:delete}
    methods: [DELETE]





